version: "3.9"

services:
  db:
    image: postgres:16
    container_name: shein_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sheindb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # cria tabela e insere dados de produtos
    ports:
      - "5432:5432"

  api:
    build: ./api
    container_name: shein_api
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/sheindb
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  dashboard:
    build: ./dashboard
    container_name: shein_dashboard
    restart: always
    environment:
      API_URL: http://api:8000
    depends_on:
      - api
    ports:
      - "8501:8501"
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0

volumes:
  postgres_data:
